#!/bin/bash

AutoUpdate () {
echo " "
echo "Enable Automatic Updates?"
echo "[1] All Updates
echo "[2] Security Updates Only
echo "[3] No"
echo " "
echo -n "> "
read opt
case $opt in
	[1]* ) echo "Enabling All Updates..."
	sudo yum install -y yum-cron && sudo wget -O /etc/yum/yum-cron.conf https://raw.githubusercontent.com/gelrii/Fedora-PostInstall/master/21/assets/yum-cron-default.conf
	echo "Enabled All Updates"
	Main
	;;
	[2]* ) echo "Enabling Security Updates..."
	sudo yum install -y yum-cron && sudo wget -O /etc/yum/yum-cron.conf https://raw.githubusercontent.com/gelrii/Fedora-PostInstall/master/21/assets/yum-cron-security.conf
	echo "Enabled Security Updates"
	Main
	;;
	[3]* ) echo "Continuing..."
	Main
	;;
	[Qq]* ) Exit
	;;
	[Rr]* ) Main
	;;
esac
}
