#!/bin/bash

Desktop_Environment () {
echo " "
echo "Select Your Desktop Environment"
echo "[1] KDE"
echo "[2] GNOME"
echo "[3] Other"
echo " "
echo -n "> "
read opt
case $opt in
	[1]* ) Remove_KDE_Packages
	;;
	[2]* ) Remove_Gnome_Packages
	;;
	[3]* ) echo "No other desktops supported by script"
	Main
	;;
	[Qq]* ) Exit
	;;
	[Rr]* ) Main
	;;
esac
}
