#!/bin/bash

Dotfiles () {
echo " "
echo "Install Gelrii Dotfiles dependancies from GitHub?"
echo " [Y]es / [N]o"
echo " "
echo -n "> "
read opt
case $opt in
	[Yy]* ) echo "Installing Dotfile Dependancies..."
	yum install -y wget lm_sensors phoronix-test-suite unrar recordmydesktop
	Main
	;;
	[Nn]* ) echo "Continuing..."
	Main
	;;
	[Qq]* ) Exit
	;;
	[Rr]* ) Main
	;;
esac
}
