#!/bin/bash

Dotfiles () {
echo " "
echo "Install asdf-git Dotfiles from GitHub?"
echo " [Y]es / [N]o"
echo " "
echo -n "> "
read opt
case $opt in
	[Yy]* ) echo "Installing Dotfile Dependancies..."
	sudo yum install -y wget lm_sensors phoronix-test-suite unrar recordmydesktop
	echo "Installing..."
	curl -o /home/`whoami`/.bashrc https://raw.githubusercontent.com/asdf-git/dotfiles/master/.bashrc && curl -o /home/`whoami`/.bash_aliases https://raw.githubusercontent.com/asdf-git/dotfiles/master/.bash_aliases && curl -o /home/`whoami`/.systeminfo.sh https://raw.githubusercontent.com/asdf-git/dotfiles/master/.systeminfo.sh && curl -o /home/`whoami`/.update.sh https://raw.githubusercontent.com/asdf-git/dotfiles/master/.update.sh
  	echo "Installed Dotfiles"
	Main
	;;
	[Nn]* ) echo "Continuing..."
	Main
	;;
	[Qq]* ) echo "Exiting..."
	exit
	;;
	[Rr]* ) Main
	;;
esac
}
