#!/bin/bash

Enable_SSH () {
echo " "
echo "Enable and Start SSH Server?"
echo "[1] Yes"
echo "[2] No"
echo " "
echo -n "> "
read opt
case $opt in
	[1]* ) echo "Enabling SSH Server..."
	systemctl enable sshd.service && systemctl start sshd.service && systemctl status sshd.service
	echo "Enabled SSH Server"
	Main
	;;
	[2]* ) echo "Continuing..."
	Main
	;;
	[Qq]* ) Exit
	;;
	[Rr]* ) Main
	;;
esac
}
