#!/bin/bash

Enable_RPMFusion () {
echo " "
echo "Enable Third-Party RPMFusion Repositories?"
echo "[1] Yes"
echo "[2] No"
echo " "
echo -n "> "
read opt
case $opt in
	[1]* ) echo "Enabling RPMFusion Repositories."
	su -c 'yum localinstall --nogpgcheck http://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm http://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm'
	Main
	;;
	[2]* ) echo "Continuing..."
	Main
	;;
	[Qq]* ) Exit
	;;
	[Rr]* ) Main
	;;
esac
}
