#!/bin/bash

Hosts_Block () {
echo " "
echo "Install Custom Hosts File to Block Ads/Malicious IPs?"
echo "[1] Yes"
echo "[2] No"
echo " "
echo -n "> "
read opt
case $opt in
	[1]* ) echo "Installing Custom Hosts File to /etc/hosts..."
	cd /etc && rm /etc/hosts && sudo curl -C - -O http://someonewhocares.org/hosts/hosts
	echo "Installed Custom Hosts File."
	Main
	;;
	[2]* ) echo "Continuing..."
	Main
	;;
	[Qq]* ) Exit
	;;
	[Rr]* ) Main
	;;
esac
}
