#!/bin/bash

Install_HTPC () {
echo "Complete Steps Necessary to Install Fedora HTPC?"
echo "[1] Yes"
echo "[2] No"
echo " "
echo -n "> "
read opt
case $opt in
	[1]* ) echo "Working..."
	echo "Enabling RPMFusion Repositories..."
	su -c 'yum localinstall --nogpgcheck http://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm http://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm'
	echo "Installing Kodi..."
	yum -y install kodi
	echo "Enabling SSH Access..."
	systemctl enable sshd.service && systemctl start sshd.service && systemctl status sshd.service
	echo "Kodi installed... Beginning Minimal Setup..."
	Minimal_Setup
	;;
	[2]* ) echo "Continuing..."
	Main
	;;
	[Qq]* ) Exit
	;;
	[Rr]* ) Main
	;;
esac
}
