#!/bin/bash

Installer () {
echo ""
echo "Select an Option:"
echo "[1] Install a useful package selection"
echo "[2] Install NVIDIA GPU Drivers [Non-Free]"
echo "[3] Install ZFS on Linux"
echo "[4] Install ownCloud"
echo "[5] Install Play on Linux [Non-Free]"
echo "[6] Install Google Chrome [Non-Free]"
echo "[7] Install Dotfile Dependencies"
echo "[8] Install VMware Guest Additions"
echo "[9] Install VirtualBox Guest Additions"
echo ""
echo "[R] Return to Main Script"
echo ""
echo -n "> "
read opt
case $opt in
	[1]* ) Install_Packages
	;;
	[2]* ) Install_NVIDIA
	;;
	[3]* ) Install_ZoL
	;;
	[4]* ) Install_ownCloud
	;;
	[5]* ) Install_POL
	;;
	[6]* ) Install_Chrome
	;;
	[7]* ) Dotfiles
	;;
	[8]* ) VM_Guest
	;;
	[9]* ) VBox_Guest
	;;
	[Qq]* ) Exit
	;;
	[Rr]* ) Main
	;;
esac
}
