#!/bin/bash

Install_Packages () {
echo " "
echo "Install Useful Package Selection?"
echo "(Some Packages Subject to Non-Free Licenses)"
echo " [Y]es / [N]o"
echo " "
echo -n "> "
read opt
case $opt in
	[Yy]* ) echo "Installing Packages..."
	yum install \
		clementine \
		eog \
		ffmpeg \
		firefox \
		gcc \
		gdouros-symbola-fonts \
		gimp \
		gnome-disk-utility \
		gpg \
		guake \
		htop \
		iftop \
		iotop \
		keepass \
		kernel-devel \
		kernel-headers \
		lm_sensors \
		mkvtoolnix \
		nano \
		ntp \
		recordmydesktop \
		remmina-plugins-rdp \
		thunderbird \
		transgui \
		tuned \
		unrar \
		vlc \
		wget \
		xchat \
		youtube-dl \
		yum-cron
	echo "Installed Packages."
	Installer
	;;
	[Nn]* ) echo "Continuing..."
	Installer
	;;
	[Qq]* ) Exit
	;;
	[Rr]* ) Main
	;;
esac
}
