#!/bin/bash

Install_HTPC () {
echo "Complete Steps Necessary to Install Fedora HTPC?"
echo " [Y]es / [N]o"
echo " "
echo -n "> "
read opt
case $opt in
	[Yy]* ) echo "Working..."
	echo "Enabling RPMFusion Repositories..."
	  su -c 'yum localinstall --nogpgcheck http://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm http://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm'
	echo "Updating System..."
	  yum update
	echo "Installing Useful HTPC Packages..."
	  yum install htop glances kodi
	echo "Enabling SSH Access..."
	  systemctl enable sshd.service && systemctl start sshd.service && systemctl status sshd.service
	echo "Removing Useless Packages..."
	  yum remove gnome-boxes gnome-documents gnome-weather gnome-contacts gnome-maps rhythmbox empathy totem evolution shotwell cheese libreoffice* gwenview dragon amarok
	echo "Cleaning Up..."
	  yum autoremove
	echo "Process Complete... Please Reboot System."
	Main
	;;
	[Nn]* ) echo "Exiting...."
	Main
	;;
	[Qq]* ) echo "Exiting..."
	exit
	;;
	[Rr]* ) Main
	;;
esac
}
