#!/bin/bash

Installer () {
echo ""
echo "Select an Option:"
echo "[i] Install a useful package selection"
echo "[n] Install NVIDIA GPU Drivers [Non-Free]"
echo "[z] Install ZFS on Linux"
echo "[o] Install ownCloud"
echo "[p] Install Play on Linux [Non-Free]"
echo "[c] Install Google Chrome [Non-Free]"
echo ""
echo "[r] Return to Main Script"
echo ""
echo -n "> "
read opt
case $opt in
	[Ii]* ) Install_Packages
	;;
	[Nn]* ) Install_NVIDIA
	;;
	[Zz]* ) Install_ZoL
	;;
	[Oo]* ) Install_ownCloud
	;;
	[Pp]* ) Install_POL
	;;
	[Cc]* ) Install_Chrome
	;;
	[Qq]* ) exit
	;;
	[Rr]* ) Main
	;;
esac
}
