#!/bin/bash

Install_ownCloud () {
echo " "
echo "Install ownCloud Desktop Sync Client?"
echo "[1] Yes"
echo "[2] No"
echo " "
echo -n "> "
read opt
case $opt in
	[1]* ) echo "Installing ownCloud..."
	cd /etc/yum.repos.d/ && wget http://download.opensuse.org/repositories/isv:ownCloud:desktop/Fedora_20/isv:ownCloud:desktop.repo && yum install owncloud-client
	echo "Installed ownCloud."
	Installer
	;;
	[2]* ) echo "Continuing..."
	Installer
	;;
	[Qq]* ) Exit
	;;
	[Rr]* ) Main
	;;
esac
}
