#!/bin/bash

Install_HTPC () {
echo "Complete Steps Necessary to Install Fedora HTPC?"
echo " [Y]es / [N]o"
echo " "
echo -n "> "
read opt
case $opt in
	[Yy]* ) echo "Working..."
	echo "Enabling RPMFusion Repositories..."
	  su -c 'yum localinstall --nogpgcheck http://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm http://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm'
	echo "Kodi installed... Beginning Minimal Setup..."
	  Minimal_Setup
	;;
	[Nn]* ) echo "Exiting...."
	Main
	;;
	[Qq]* ) echo "Exiting..."
	exit
	;;
	[Rr]* ) Main
	;;
esac
}
