#!/bin/bash

Install_POL () {
echo " "
echo "Install PlayOnLinux?"
echo "[1] Yes"
echo "[2] No"
echo " "
echo -n "> "
read opt
case $opt in
	[1]* ) echo "Installing PlayOnLinux..."
	# Note to script maintainers: The first command in the below line will need updating when the repo is updated.
	wget -O /tmp/playonlinux.rpm http://rpm.playonlinux.com/playonlinux-yum-4-1.noarch.rpm && yum -y install /tmp/playonlinux.rpm && yum install playonlinux
	echo "Installed PlayOnLinux."
	Installer
	;;
	[2]* ) echo "Continuing..."
	Installer
	;;
	[Qq]* ) Exit
	;;
	[Rr]* ) Main
	;;
esac
}
