#!/bin/bash
Install_NVIDIA () {
echo ""
echo "Install Proprietary NVIDIA Drivers?"
echo ""
echo "This option is intended for people running a machine with an"
echo "NVIDIA GeForce 8/9/200/300/400/500/600/700 graphics adapter."
echo ""
echo "Please make sure to run the option to enable the RPMFusion"
echo "repositories before running this option."
echo ""
echo "Please also make sure you run the \"Update System\" option"
echo "and reboot when it has completed, before running this option."
echo ""
echo " [Y]es / [N]o"
echo -n "> "
read opt
case $opt in
[Yy]* ) echo "Installing Proprietary NVIDIA Drivers..."
yum install akmod-nvidia xorg-x11-drv-nvidia-libs kernel-devel acpid vdpauinfo libva-vdpau-driver libva-utils && echo "Generating New initramfs..." && mv /boot/initramfs-$(uname -r).img /boot/initramfs-$(uname -r)-nouveau.img && dracut /boot/initramfs-$(uname -r).img $(uname -r)
echo "NVIDIA Drivers Installed."
Installer
;;
[Nn]* ) echo "Continuing..."
Installer
;;
[Qq]* ) echo "Exiting..."
exit
;;
[Rr]* ) Main
;;
esac
}
