#!/bin/bash

Install_Chrome () {
echo " "
echo "Install Google Chrome? [Non-Free Software!]"
echo "[1] Yes"
echo "[2] No"
echo " "
echo -n "> "
read opt
case $opt in
	[1]* ) echo "Installing Google Chrome..."
	sudo curl -o /etc/yum.repos.d/google-chrome.repo https://raw.githubusercontent.com/asdf-git/Fedora-PostInstall/master/$(rpm -E %fedora)/assets/google-chrome.repo && sudo yum install google-chrome-stable
	echo "Installed Google Chrome."
	Installer
	;;
	[2]* ) echo "Continuing..."
	Installer
	;;
	[Qq]* ) Exit
	;;
	[Rr]* ) Main
	;;
esac
}
