#!/bin/bash

Install_Packages () {
echo " "
echo "Install Useful Package Selection?"
echo "(Some Packages Subject to Non-Free Licenses)"
echo " [Y]es / [N]o"
echo " "
echo -n "> "
read opt
case $opt in
	[Yy]* ) echo "Installing Packages..."
	yum install \
	guake \\ # Quake-style drop-down terminal
	yum-cron \\ # Enables scheduling of automatic updates
	clementine \
	transgui \\ # Remote GUI for Transmission BitTorrent client
	htop \
	nano \
	tuned \
	xchat \
	vlc \
	lm_sensors \
	iotop \
	iftop \
	gcc \
	kernel-headers \
	kernel-devel \
	gnome-disk-utility \\ # Install GDU for environments other than GNOME
	firefox \
	thunderbird \
	keepass \
	remmina-plugins-rdp \\ # Install Remmina GUI RDP client
	ffmpeg mkvtoolnix \
	youtube-dl \
	eog \
	recordmydesktop \
	gpg \
	gimp \
	wget \
	ntp \
	unrar \
	gdouros-symbola-fonts # Fonts to enable emoji support (http://fedoramagazine.org/how-to-get-emoji-to-display-on-fedora/)
	echo "Installed Packages."
	Installer
	;;
	[Nn]* ) echo "Continuing..."
	Installer
	;;
	[Qq]* ) echo "Exiting..."
	exit
	;;
	[Rr]* ) Main
	;;
esac
}
