#!/bin/bash

Main () {
echo ""
echo "Select an Option:"
echo "[u] System Update"
echo "[p] Remove Packages"
echo "[r] Enable RPMFusion Repositories"
echo "[i] Install Items"
echo "[s] Enable SSH"
echo "[b] Block Ads etc. with Custom Hosts File"
echo "[h] Install as HTPC"
echo "[d] Install Dotfiles"
echo "[m] Complete Minimal Setup (Automated)"
echo "[v] Install VMware Guest Additions"
echo "[x] Install VirtualBox Guest Additions"
echo "[a] Enable Automatic Updates"
echo ""
echo "[q] Exit"
#echo "7)Fix Fonts" #Deprecated until Infinality repo available for Fedora 21
echo ""
echo -n "> "
read opt
case $opt in
	[Uu]* ) System_Update
	;;
	[Pp]* ) Desktop_Environment
	;;
	[Rr]* ) Enable_RPMFusion
	;;
	[Ii]* ) Installer
	;;
	[Ss]* ) Enable_SSH
	;;
	[Bb]* ) Hosts_Block
	;;
	[Hh]* ) Install_HTPC
	;;
	[Dd]* ) Dotfiles
	;;
	[Mm]* ) Minimal_Setup
	;;
	[Vv]* ) VM_Guest
	;;
	[Xx]* ) VBox_Guest
	;;	
	[Aa]* ) AutoUpdate
	;;
#	[Ff]* ) Fix_Fonts #Deprecated until Infinality repo available for Fedora 21
#	;; #Deprecated until Infinality repo available for Fedora 21
	[Qq]* ) exit
	;;
	[Rr]* ) Main
	;;
esac
}
