#!/bin/bash

Main () {
echo ""
echo "Select an Option:"
echo "[1] System Update"
echo "[2] Remove Packages"
echo "[3] Enable RPMFusion Repositories"
echo "[4] Install Items"
echo "[5] Enable SSH"
echo "[6] Block Ads etc. with Custom Hosts File"
echo "[7] Install as HTPC"
echo "[8] Complete Minimal Setup (Automated)"
echo "[9] Enable Automatic Updates"
echo ""
echo "[q] Exit"
#echo "7)Fix Fonts" #Deprecated until Infinality repo available for Fedora 21
echo ""
echo -n "> "
read opt
case $opt in
	[1]* ) System_Update
	;;
	[2]* ) Desktop_Environment
	;;
	[3]* ) Enable_RPMFusion
	;;
	[4]* ) Installer
	;;
	[5]* ) Enable_SSH
	;;
	[6]* ) Hosts_Block
	;;
	[7]* ) Install_HTPC
	;;
	[8]* ) Minimal_Setup
	;;
	[9]* ) AutoUpdate
	;;
#	[Ff]* ) Fix_Fonts #Deprecated until Infinality repo available for Fedora 21
#	;; #Deprecated until Infinality repo available for Fedora 21
	[Qq]* ) Exit
	;;
	[Rr]* ) Main
	;;
esac
}
