#!/bin/bash

Minimal_Setup () {
echo ""
echo "Complete Minimal Useful Install Procedure?"
echo ""
echo "This section of the script will update the system"
echo "and install a minimal set of useful packages,"
echo "currently: \"glances, htop, nano, wget, yum-cron\"."
echo ""
echo "It will then enable SSH access, and remove most of"
echo "the default GNOME packages to slim down the install as"
echo "much as possible."
echo ""
echo "This section will not enable the RPMFusion"
echo "repositories. If you are running the HTPC configuration"
echo "script, these will have already been enabled."
echo ""
echo " [Y]es / [N]o"
echo " "
echo -n "> "
read opt
case $opt in
	[Yy]* ) echo "Working..."
	echo "Updating System..."
	  yum update -y
	echo "Installing (Minimal) Useful Packages..."
	  yum install -y \
	  	glances \
	  	htop \
	  	nano \
	  	wget \
	  	yum-cron
	echo "Enabling SSH Access..."
	  systemctl enable sshd.service && systemctl start sshd.service && systemctl status sshd.service
	echo "Removing Non-Useful Packages..."
	  yum remove -y \
	  	amarok \
	  	cheese \
	  	devassistant \
	  	dragon \
	  	empathy \
	  	evolution \
	  	gnome-boxes \
	  	gnome-contacts \
	  	gnome-documents \
	  	gnome-maps \
	  	gnome-software \
	  	gnome-weather \
	  	gwenview \
	  	java* \
	  	k3b \
	  	libreoffice* \
	  	rhythmbox \
	  	shotwell \
	  	totem \
	  	transmission*
	echo "Cleaning Up..."
	  yum autoremove -y
	echo "Process Complete... Please Reboot System."
	Main
	;;
	[Nn]* ) echo "Exiting...."
	Main
	;;
	[Qq]* ) echo "Exiting..."
	exit
	;;
	[Rr]* ) Main
	;;
esac
}
