#!/bin/bash

Remove_Gnome_Packages () {
echo "GNOME Selected"
echo "Remove (Mostly) Useless GNOME Packages?"
echo " [Y]es / [N]o"
echo " "
echo -n "> "
read opt
case $opt in
	[Yy]* ) echo "Removing..."
	yum remove rhythmbox empathy totem evolution shotwell cheese
	echo "Removed Useless GNOME Packages."
	Main
	;;
	[Nn]* ) echo "Continuing..."
	Main
	;;
	[Qq]* ) Exit
	;;
	[Rr]* ) Main
	;;
esac
}
