#!/bin/bash

Remove_KDE_Packages () {
echo "KDE Selected"
echo "Remove (Mostly) Useless KDE Packages?"
echo "[1] Yes"
echo "[2] No"
echo " "
echo -n "> "
read opt
case $opt in
	[1]* ) echo "Removing..."
	yum remove gwenview dragon amarok
	echo "Removed Useless KDE Packages."
	Main
	;;
	[2]* ) echo "continuing..."
	Main
	;;
	[Qq]* ) Exit
	;;
	[Rr]* ) Main
	;;
esac
}
