#!/bin/bash

Remove_Gnome_Packages () {
echo "GNOME Selected"
echo "Remove (Mostly) Useless GNOME Packages?"
echo "[1] Yes"
echo "[2] No"
echo ""
echo -n "> "
read opt
case $opt in
	[1]* ) echo "Removing..."
	yum remove rhythmbox empathy totem evolution shotwell cheese
	echo "Removed Useless GNOME Packages."
	Main
	;;
	[2]* ) echo "Continuing..."
	Main
	;;
	[Qq]* ) Exit
	;;
	[Rr]* ) Main
	;;
esac
}
