#!/bin/bash

System_Update () {
echo " "
echo "Update System?"
echo "[1] Yes"
echo "[2] No"
echo " "
echo -n "> "
read opt
case $opt in
	[1]* ) echo "Updating System..."
	yum update
	echo "Updated System."
	AutoUpdate
	;;
	[2]* ) echo "Continuing..."
	AutoUpdate
	;;
	[Qq]* ) Exit
	;;
	[Rr]* ) Main
	;;
esac
}
