#!/bin/bash

VBox_Guest () {
echo " "
echo "Install VirtualBox Guest Additions?"
echo ""
echo "Please enable the RPMFusion repositories"
echo "before using this option."
echo ""
echo "[1] Yes"
echo "[2] No"
echo " "
echo -n "> "
read opt
case $opt in
  [1]* ) echo "Installing VMware Guest Additions..."
  yum install VirtualBox-guest
  echo "Installed VirtualBox Guest Additions"
  Installer
  ;;
  [2]* ) echo "Continuing..."
  Installer
  ;;
  [Qq]* ) Exit
  ;;
  [Rr]* ) Main
  ;;
esac
}
