#!/bin/bash

VM_Guest () {
echo " "
echo "Install VMware Guest Additions?"
echo ""
echo "Please complete an update-and-reboot cycle"
echo "before using this option."
echo ""
echo "[1] Yes"
echo "[2] No"
echo " "
echo -n "> "
read opt
case $opt in
	[1]* ) echo "Installing VMware Guest Additions..."
	yum install open-vm-tools open-vm-tools-desktop
	echo "Installed VMware Guest Additions"
	Installer
	;;
	[2]* ) echo "Continuing..."
	Installer
	;;
	[Qq]* ) Exit
	;;
	[Rr]* ) Main
	;;
esac
}
