#!/bin/bash

VM_Guest () {
echo " "
echo "Install VMware Guest Additions?"
echo ""
echo "Please complete an update-and-reboot cycle"
echo "before using this option."
echo ""
echo " [Y]es / [N]o"
echo " "
echo -n "> "
read opt
case $opt in
	[Yy]* ) echo "Installing VMware Guest Additions..."
	yum install open-vm-tools open-vm-tools-desktop
	echo "Installed VMware Guest Additions"
	Main
	;;
	[Nn]* ) echo "Continuing..."
	Main
	;;
	[Qq]* ) echo "Exiting..."
	exit
	;;
	[Rr]* ) Main
	;;
esac
}
