#!/bin/bash
Install_NVIDIA () {
echo ""
echo "Install Proprietary NVIDIA Drivers?"
echo ""
echo "Please make sure to run the option to enable the RPMFusion"
echo "repositories before running this option."
echo ""
echo "Please also make sure you run the \'Update System\' option"
echo "and reboot when it has completed, before running this option."
echo " [Y]es / [N]o"
echo ""
echo -n "> "
read opt
case $opt in
[Yy]* ) echo "Installing Proprietary NVIDIA Drivers..."
yum install akmod-nvidia xorg-x11-drv-nvidia-libs kernel-devel acpid vdpauinfo libva-vdpau-driver libva-utils && mv /boot/initramfs-$(uname -r).img /boot/initramfs-$(uname -r)-nouveau.img && dracut /boot/initramfs-$(uname -r).img $(uname -r)
echo "NVIDIA Drivers Installed."
Installer
;;
[Nn]* ) echo "Continuing..."
Installer
;;
[Qq]* ) echo "Exiting..."
exit
;;
[Rr]* ) Main
;;
esac
}
