#!/bin/bash

Enable_RPMFusion () {
echo " "
echo "Enable Third-Party RPMFusion Repositories?"
echo " [Y]es / [N]o"
echo " "
echo -n "> "
read opt
case $opt in
	[Yy]* ) echo "Enabling RPMFusion Repositories."
	# Update gpg to manage RPMFusion signing keys
	sudo dnf install -y gpg
	
	# Install RPMFusion free repo key (see http://rpmfusion.org/keys)
	gpg --keyserver pgp.mit.edu --recv-keys 97F4D1C1
	
	# Install RPMFusion nonfree repo key (see http://rpmfusion.org/keys)
	gpg --keyserver pgp.mit.edu --recv-keys A6708DA3
	
	# Install RPMFusion repositories
	sudo dnf install \
		http://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm \
		http://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm
	
	# Return to main script
	Main
	;;
	[Nn]* ) echo "Continuing..."
	Main
	;;
	[Qq]* ) Exit
	;;
	[Rr]* ) Main
	;;
esac
}
