#!/bin/bash

Hosts_Block () {
echo " "
echo "Install Custom Hosts File to Block Ads/Malicious IPs?"
echo " [Y]es / [N]o"
echo " "
echo -n "> "
read opt
case $opt in
	[Yy]* ) echo "Installing Custom Hosts File to /etc/hosts..."
	  cd /etc
	  sudo rm /etc/hosts
	  sudo curl -C - -O http://someonewhocares.org/hosts/hosts
	echo "Installed Custom Hosts File."
	Main
	;;
	[Nn]* ) echo "Continuing..."
	Main
	;;
	[Qq]* ) Exit
	;;
	[Rr]* ) Main
	;;
esac
}
