#!/bin/bash

Installer () {
echo ""
echo "Select an Option:"
echo "[I] Install a useful package selection"
echo "[T] Install Tor Browser Bundle"
echo "[D] Install Tor Service (Can Run Alongside TBB)"
echo "[N] Install NVIDIA GPU Drivers [Non-Free]"
#echo "[Z] Install ZFS on Linux" ## Temporarily disabled
echo "[O] Install ownCloud Client"
echo "[P] Install Play on Linux [Non-Free]"
echo "[C] Install Google Chrome [Non-Free]"
echo "[S] Install Steam Game Client [Non-Free]"
echo "[G] Install VMware Guest Additions"
echo "[X] Install VirtualBox Guest Additions"
echo "[V] Install VirtualBox"
echo "[A] Install Arc Theme (GNOME)"
echo "[W] Enable Additional Window Buttons (GNOME)"
echo "[M] Install HQ mpv Config"
echo ""
echo "[R] Return to Main Script"
echo "[Q] Exit"
echo ""
echo -n "> "
read opt
case $opt in
	[Ii]* ) Install_Packages;;
	[Tt]* ) Install_TBB;;
	[Dd]* ) Install_Tor;;
	[Nn]* ) Install_NVIDIA;;
#	[Zz]* ) Install_ZoL;; ## Temporarily disabled
	[Oo]* ) Install_ownCloud;;
	[Pp]* ) Install_POL;;
	[Cc]* ) Install_Chrome;;
	[Gg]* ) VM_Guest;;
	[Xx]* ) VBox_Guest;;
	[Vv]* ) Install_VBox;;
	[Ss]* ) Install_Steam;;
	[Aa]* ) ArcTheme;;
	[Ww]* ) WindowButtons;;
	[Mm]* ) MPVConf;;
	[Qq]* ) Exit;;
	[Rr]* ) Main;;
esac
}
