#!/bin/bash

Install_POL () {
echo " "
echo "Install PlayOnLinux?"
echo " [Y]es / [N]o"
echo " "
echo -n "> "
read opt
case $opt in
	[Yy]* ) echo "Installing PlayOnLinux..."
	# Note to script maintainers: The first command in the below line will need updating when the repo is updated.
	  sudo dnf -y install http://rpm.playonlinux.com/playonlinux-yum-4-1.noarch.rpm
	  sudo dnf install playonlinux
	echo "Installed PlayOnLinux."
	Installer
	;;
	[Nn]* ) echo "Continuing..."
	Installer
	;;
	[Qq]* ) Exit
	;;
	[Rr]* ) Main
	;;
esac
}
