#!/bin/bash

MPVConf () {
echo ""
echo "Install HQ mpv Config?"
echo ""
echo " [Y]es / [N]o"
echo ""
echo -n "> "
read opt
case $opt in
	[Yy]* ) echo "Installing HQ mpv Config..."
	sudo rm $HOME/.config/mpv/mpv.conf
	#curl -o $HOME/.config/mpv/mpv.conf https://raw.githubusercontent.com/ajhaydock/FedPo/master/$(rpm -E %fedora)/assets/mpv.conf
	sudo mv /tmp/Fedora-Postinstall/$release/assets/mpv.conf
	echo "Installed HQ mpv Config."
	Installer
	;;
	[Nn]* ) echo "Continuing..."
	Installer
	;;
	[Qq]* ) Exit
	;;
	[Rr]* ) Main
	;;
esac
}
