#!/bin/bash

Remove_Useless () {
echo "Remove (Mostly) Useless Default Packages?"
echo " [Y]es / [N]o"
echo " "
echo -n "> "
read opt
case $opt in
	[Yy]* ) echo "Removing..."
	cat /tmp/Fedora-Postinstall/$release/config/dnfremove.txt | sed '/^#/d' | tr -d '\n' > /tmp/Fedora-Postinstall/$release/config/dnfremove-stripped.txt && sudo dnf remove `cat /tmp/Fedora-Postinstall/$release/config/dnfremove-stripped.txt`
	sudo dnf autoremove
	echo "Removed Useless Default Packages."
	Main
	;;
	[Nn]* ) echo "Continuing..."
	Main
	;;
	[Qq]* ) Exit
	;;
	[Rr]* ) Main
	;;
esac
}
