#!/bin/bash

tbb() {
# Make root .TBB/ directory if it doesn't exist, then attempt to remove any existing TBB installations in it
echo "Attempting to remove old Tor Browser installations."
echo "Please ignore any 'Not Found' error on the following line."
mkdir -p /$tbbdir
rm -r /$tbbdir/tor-browser_en-US/
# rsync to destination dir
rsync -avsh /tmp/tor-browser_en-US/ /$tbbdir/tor-browser_en-US/
# Set permissions, just to make sure
sudo chown -R `id -un`:`id -gn` /$tbbdir
sudo chmod 770 -R /$tbbdir
# Remove already registered TBB applications from app menu
sudo rm /home/$luser/.local/share/applications/start-tor-browser.desktop
# Register TBB as an application in the applications menu
echo ""
echo "#####"
echo "Registering Tor Browser application."
echo "If this step appears to hang after confirming success, try pressing Ctrl + C to continue the script."
echo "#####"
echo ""
cd /$tbbdir/tor-browser_en-US/
./start-tor-browser.desktop --register-app
# Install torsocks & tor-arm to allow monitoring & proxying of other system applications
## (DEPRECATED: Now set up to use default config and Tor service instead)
#sudo dnf install -y torsocks tor-arm
# Download appropriate config for use with TBB
#sudo rm /etc/tor/torsocks.conf
#sudo curl -o /etc/tor/torsocks.conf https://raw.githubusercontent.com/ajhaydock/FedPo/master/$(rpm -E %fedora)/assets/torsocks.conf
# Return to Installer script
Installer
}
